micronaut:
  server:
    context-path: /v1/example
  application:
    name: template
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
    dialect: H2
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
jpa.default.properties.hibernate.hbm2ddl.auto: update

petStore:
  url: https://petstore.swagger.io/v2
